# 1
INSERT INTO sales_list.sales (date_time,
                              title,
                              market_place,
                              delivery_service,
                              payment_method,
                              is_my_packing,
                              is_own,
                              notes,
                              order_status,
                              sold_at_price,
                              sold_including_expenses,
                              payout_for_cooperation,
                              payout_percentage,
                              my_profit)
VALUES ('2019-08-02 10:55:47',
        'Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)',
        'OLX',
        'OLX-доставка',
        'Наложенный платеж',
        true,
        false,
        '',
        'SUCCESS',
        185.0,
        179.0,
        71.6,
        40.0,
        107.4);


# 2
INSERT INTO sales_list.sales (date_time,
                              title,
                              market_place,
                              delivery_service,
                              payment_method,
                              is_my_packing,
                              is_own,
                              notes,
                              order_status,
                              sold_at_price,
                              sold_including_expenses,
                              payout_for_cooperation,
                              payout_percentage,
                              my_profit)
VALUES ('2019-08-05 13:42:12',
        'Doctor''s Best Гиалуроновая кислота и сульфат хондроитина 180 капсул',
        'OLX',
        'Новая Почта',
        'Полная предоплата',
        true,
        true,
        'Карта клиента НП (+2 грн.)',
        'SUCCESS',
        310.0,
        310.0,
        310.0,
        0,
        310.0);


# 3
INSERT INTO sales_list.sales (date_time,
                              title,
                              market_place,
                              delivery_service,
                              payment_method,
                              is_my_packing,
                              is_own,
                              notes,
                              order_status,
                              sold_at_price,
                              sold_including_expenses,
                              payout_for_cooperation,
                              payout_percentage,
                              my_profit)
VALUES ('2019-08-06 12:08:40',
        'Очки Jagermeister Глянцевые Черные (старого образца)',
        'OLX',
        'Новая Почта',
        'Полная предоплата',
        true,
        false,
        'Карта клиента НП (+2 грн.)',
        'SUCCESS',
        106.0,
        106.0,
        42.4,
        40,
        63.6);


# 4
INSERT INTO sales_list.sales (date_time,
                              title,
                              market_place,
                              delivery_service,
                              payment_method,
                              is_my_packing,
                              is_own,
                              notes,
                              order_status,
                              sold_at_price,
                              sold_including_expenses,
                              payout_for_cooperation,
                              payout_percentage,
                              my_profit)
VALUES ('2019-08-07 09:17:03',
        'Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)',
        'OLX',
        'Новая Почта',
        'OLX-доставка',
        true,
        false,
        '',
        'SUCCESS',
        185.0,
        179.0,
        71.6,
        40.0,
        107.4);
