package org.saleslist;

import org.saleslist.enums.DeliveryServiceEnum;
import org.saleslist.enums.MarketPlaceEnum;
import org.saleslist.enums.OrderStatusEnum;
import org.saleslist.enums.PaymentMethodEnum;
import org.saleslist.model.Product;
import org.saleslist.repository.jdbc.JdbcProductRepository;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;

public class Start {

	public static void main(String[] args) {
		try(ConfigurableApplicationContext appCtx = new ClassPathXmlApplicationContext("spring/spring-app.xml", "spring/spring-db.xml")) {
			System.out.println("Bean definition names: " + Arrays.toString(appCtx.getBeanDefinitionNames()));

			JdbcProductRepository productRepository = appCtx.getBean(JdbcProductRepository.class);

			System.out.println("   =========   ");


//			List<Product> productList = productRepository.getAll(100);
//			for (Product p : productList) {
//				System.out.println("userId null, LocalDateTime.of(" + p.getDateTime() + "), \"" + p.getTitle() + "\", MarketPlaceEnum." + p.getMarketPlace() + ", DeliveryServiceEnum." + p.getDeliveryService() + ", PaymentMethodEnum." + p.getPaymentMethod() + ", OrderStatusEnum." + p.getOrderStatus() + ", new BigDecimal(\"" + p.getSpent() + "\"), new BigDecimal(\"" + p.getSoldAtPrice() + "\"), " + p.getPayoutPercentage() + ", \"" + p.getNotes() + "\"");
//			}

			productRepository.save(new Product(null, LocalDateTime.of(2020,11,12,15,24), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 3 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("600"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,11,11,15,24), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("215"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,11,9,10,19), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("215"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,11,8,14,49), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("215"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,11,6,15,15), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("215"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,10,21,20,40), "Медь Twinlab 2 мг 100 капсул (Новая!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("130"), new BigDecimal("0"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,10,19,14,16), "Джемпер мужской флисовый Pearl Izumi размер М Салатовый", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,25,16,55), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,20,16,52), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,20,16,51), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,17,16,41), "Набор Велокомпьютер GPS с фарой Lezyne Mega XL Smart Loaded", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("5500"), new BigDecimal("3528.87"), 0, "eBay"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,17,16,31), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,16,16,21), "Солнцезащитные очки Jagermeister Green (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("135"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,16,16,11), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,14,16,9), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,8,16,8), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,8,16,7), "Солнцезащитные очки Jagermeister Green (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("135"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,7,16,6), "Новые Стаканы (бокалы) Baileys с золотым лого - 7 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,7,16,5), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,6,16,4), "Солнцезащитные очки Jagermeister Green (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("135"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,6,16,3), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,3,16,2), "Новые Фляги Elite SuperCorsa 750 мл Цена за 2 штуки!", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("320"), new BigDecimal("290"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,9,2,16,1), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,30,13,24), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 5 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("750"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,26,13,12), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,26,13,11), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,23,13,9), "Новые Стаканы (бокалы) Baileys с золотым лого - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("140"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,21,13,8), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,18,13,7), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 3 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("500"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,9,13,7), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.DENIED, new BigDecimal("0"), new BigDecimal("0"), 0, "Чувак отказался, взял только зеленые"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,9,13,6), "Солнцезащитные очки Jagermeister Green (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("150"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,5,13,5), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,5,13,4), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,8,4,13,3), "Новые Фляги Elite Corsa 550 мл Цена за 2 штуки!", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("270"), new BigDecimal("245"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,30,13,41), "Велоодежда джерси Eliel", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("198"), new BigDecimal("155"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,29,13,31), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,25,13,21), "Новые фирменные кружки Captain Morgan - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("100"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,23,13,11), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("190"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,21,13,9), "Новые Фляги Elite Super Corsa 750 мл Цена за 2 штуки!", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("300"), new BigDecimal("295"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,16,13,8), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("330"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,16,13,7), "Новые Шоты Рюмки Стопки Jose Cuervo", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("330"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,16,13,6), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,15,13,5), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("190"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,6,13,4), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("190"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,4,13,3), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт. + Солнцезащитные очки Jagermeister Green (Новые, в упаковке!) - 1 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("500"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,3,13,2), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("190"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,7,2,13,1), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,30,12,59), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("190"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,28,12,58), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("190"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,28,12,57), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("180"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,22,12,56), "Замковые эксцентрики PZ Racing CR5.3Q MTB Black б/у", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("340"), new BigDecimal("0"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,11,12,55), "Новые Стаканы для виски Johnnie Walker - 6 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "100 ПРОДАЖ"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,9,12,54), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,9,12,53), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,8,12,52), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,8,12,51), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,6,5,12,50), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,50), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 3 шт", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("500"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,42), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 3 шт", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("500"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,40), "Чехол GIYO для инструментов под флягодержатель Цена за 2 шт", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("250"), new BigDecimal("200"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,39), "Новые Стаканы Johnnie Walker - 2 шт", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("160"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,38), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,37), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,34), "Велокомпьютер/навигатор GPS Lezyne Mega XL Metallic Red", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("4999"), new BigDecimal("3728.44"), 0, "Карта клиента НП (+2 грн.); Amazon; Предоплата 100 грн."), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,32), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("168.58"), 0, "Карта клиента НП (+2 грн.); Aliexpress; Реклама 34.3 грн."), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,31), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,31), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,30), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,28), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,27), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,25), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,12), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,5,2,12,2), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,28,15,31), "Умный задний вело фонарь фара Meroca", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("365"), new BigDecimal("134.28"), 0, "Aliexpress"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,24,13,15), "Новые Стаканы для виски Johnnie Walker - 4 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("320"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,23,13,14), "Новая Передняя фара (свет) Lezyne Lite Drive 1000XL Black", MarketPlaceEnum.CONTACTS, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("1444"), new BigDecimal("1004.83"), 0, "Карта клиента НП (+2 грн.); eBay"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,23,13,13), "Велокомпьютер/навигатор GPS Lezyne Super Pro + Front Mount", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("3000"), new BigDecimal("1676.67"), 0, "Встреча"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,23,13,12), "Велокомпьютер/навигатор GPS Lezyne Super Pro", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("3000"), new BigDecimal("1977.98"), 0, "Встреча"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,23,13,10), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,18,13,9), "Новые Стаканы Johnnie Walker - 5 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("325"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,14,13,8), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,13,13,7), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,13,13,6), "Комплект велофар Lezyne 800XL & Strip Drive 150 Pair", MarketPlaceEnum.CONTACTS, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("1800"), new BigDecimal("1244.02"), 0, "eBay"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,11,13,6), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,10,13,6), "Солнцезащитные очки Jagermeister Green (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.PARTIAL_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("160"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.); Предоплата 100 грн"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,10,13,5), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!) - 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,5,13,4), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,2,13,3), "Новые Стаканы Johnnie Walker - 4 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("260"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,2,13,1), "Велокомпьютер Lezyne Macro GPS Black", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("1500"), new BigDecimal("1248.7"), 0, "eBay"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,4,1,13,1), "Велокомпьютер Lezyne Macro GPS Black", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.DENIED, new BigDecimal("0"), new BigDecimal("0"), 0, "Чувак завтыкал"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,30), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,28), "Новые Стаканы Johnnie Walker - 5 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("250"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,25), "Новые Стаканы Johnnie Walker - 12 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("600"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,22), "Регулируемое зеркало заднего вида на шлем", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("95"), new BigDecimal("0"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,20), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,19), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,18), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,17), "Датчик каденса и скорости для Garmin, Lezyne, Bryton", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("650"), new BigDecimal("0"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,16), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,15), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,10), "Солнцезащитные очки Jagermeister Black-Orange (Новые, в упаковке!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,9), "Подседельная сумка Topeak Aero Wedge Large", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("400"), new BigDecimal("0"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,3,1,14,9), "Новые Флягодержатели Elite Custom Race Black-Red 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("500"), new BigDecimal("380"), 0, "Карта клиента НП (+2 грн.); BikeInn"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,2,26,14,8), "Футболка Eighty Eight (88) New York XL Вишневая", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("130"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,2,22,14,6), "Новая Передняя фара (свет) Lezyne Lite Drive 800XL Black", MarketPlaceEnum.CONTACTS, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("1100"), new BigDecimal("1060.33"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,2,14,14,4), "Новая Передняя фара (свет) Lezyne Lite Drive 800XL Black", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("1150"), new BigDecimal("1060.33"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,1,19,13,0), "Новые Стаканы Johnnie Walker - 5 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2020,1,18,13,0), "Новый Велокомпьютер GPS Garmin Edge 520 Plus + Чехол + Стекло!", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("6000"), new BigDecimal("5945.23"), 0, "eBay"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2020,1,13,13,0), "Съемник каретки для велосипеда Bike Hand YC-26BB (новый!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("150"), new BigDecimal("0"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,12,31,12,0), "Новые фирменные кружки Captain Morgan", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("250"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,12,30,12,0), "Новые Стаканы Captain Morgan Captain & Cola", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("300"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,12,25,12,0), "Новые фирменные кружки Captain Morgan", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("60"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,12,19,12,0), "Смазки цепи Muc-Off для сухой/мокрой погоды Dry/Wet Lube 120 мл", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("265"), new BigDecimal("147.02"), 0, "Wiggle 29.09.2019"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,12,18,12,0), "Комплект велофар Lezyne Macro 800XL & Micro Drive Pair Black", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("1777"), new BigDecimal("1376.33"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,12,15,12,0), "Новая Передняя фара (свет) Lezyne Lite Drive 800XL Black", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("1150"), new BigDecimal("1060.33"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,11,11,12,2), "Смазки цепи Muc-Off для сухой/мокрой погоды Dry/Wet Lube 120 мл", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("245"), new BigDecimal("147.02"), 0, "Использована скидка НП (-6 грн.); Wiggle 29.09.2019"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,11,11,12,0), "СРОЧНО! Футболка Ecko Premio 15, размер М, Темно-синяя", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("150"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 103);
			productRepository.save(new Product(null, LocalDateTime.of(2019,10,31,12,0), "Солнцезащитные очки Jagermeister Green (Новые, в упаковке!) 2 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("270"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,10,25,13,0), "Новые Шоты Рюмки Стопки Текила Sauza (Сауза) 3 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("165"), new BigDecimal("0"), 40, "Использована скидка НП (-6 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,10,21,13,0), "Стаканы (бокалы) Baileys с золотым лого (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("50"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,10,11,14,0), "СРОЧНО! Сканер Epson Perfection 1270 USB А4", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("415"), new BigDecimal("0"), 40, ""), 102);
			productRepository.save(new Product(null, LocalDateTime.of(2019,10,11,13,0), "Съемник шатунов для велосипеда Bike Hand YC-215CB (б/у)", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("108"), new BigDecimal("0"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,10,8,13,0), "Набор бокалов для вина Pasabahce Service Line Casablanka 51258 12 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("300"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,10,6,13,0), "Стаканы (бокалы) Baileys с золотым лого (Новые!) 12 шт.", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("700"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,30,15,0), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("150"), new BigDecimal("0"), 40, "Тот же заказ"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,30,13,0), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("166"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,25,13,0), "СРОЧНО! Велоформа (джерси + трусы с лямками) Monton Pro Sky, размер L", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("1100"), new BigDecimal("480"), 0, "Покупал форму 5 лет назад"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,24,13,0), "СРОЧНО! Велокомпьютер Lezyne Mega C GPS Black", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.PARTIAL_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("4650"), new BigDecimal("3764.92"), 0, "Карта клиента НП (+2 грн.); Предоплата 200 грн; eBay"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,19,14,0), "Новые зауженные мужские джинсы 16 Revolution 88 M8315 W34 x L32", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("200"), new BigDecimal("0"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,19,13,0), "Б/У Велоштаны демисезонные Cannondale с ветрозащитой, размер L", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("170"), new BigDecimal("0"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,16,13,0), "Теодор Драйзер - Финансист, Сестра Керри (Цена за 2 книги!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("50"), new BigDecimal("0"), 0, ""), 102);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,13,13,0), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("172"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,10,13,0), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("172"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,8,13,0), "Стаканы (бокалы) Baileys с золотым лого 6 шт. в упаковке (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("350"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,9,7,13,0), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("160"), new BigDecimal("0"), 40, ""), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,31,13,0), "Силиконовый чехол для GoPro Hero5/6/7 Blue (Новый в пакете!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("95"), new BigDecimal("0"), 0, "Карта клиента НП (+2 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,27,13,0), "СРОЧНО! Задний переключатель Shimano ACERA RD-M390 Black (б/у)", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("300"), new BigDecimal("0"), 0, "Покупка упаковки"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,22,13,0), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.COLLECTION_IN_PERSON, PaymentMethodEnum.CASH, OrderStatusEnum.SUCCESS, new BigDecimal("176"), new BigDecimal("0"), 40, "Покупка упаковки"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,20,13,0), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("196"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,15,13,0), "Тестер воды Xiaomi Mi TDS Pen", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("160"), new BigDecimal("0"), 0, "Использована скидка НП (-6 грн.)"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,14,13,0), "Смазка цепи для сухой погоды Muc-Off Dry Lube 120 мл (новая!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("286"), new BigDecimal("0"), 0, "Покупка упаковки"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,12,13,0), "Очки Jagermeister Black (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("6"), 40, "Покупка упаковки"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,11,13,0), "Now Foods Глицин 1000 мг 100 капсул (новая, закрытая банка)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("291"), new BigDecimal("6"), 0, "Покупка упаковки"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,10,13,0), "Очки Jagermeister Black (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("195"), new BigDecimal("6"), 40, "Покупка упаковки"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,9,13,0), "Защита колена и голени SixSixOne (661) Comp Knee, размер M, White", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.CASH_ON_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("740"), new BigDecimal("0"), 0, "Покупка упаковки"), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,7,16,3), "Очки Jagermeister Black (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("180"), new BigDecimal("6"), 40, "Покупка упаковки"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,7,13,0), "Велофара (свет) передняя Lezyne Micro Drive 450XL Black (как новая!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("710"), new BigDecimal("0"), 0, ""), 104);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,7,12,41), "Шоты/стопки/рюмки Jagermeister 6 шт. Черные (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("418"), new BigDecimal("8"), 40, "Покупка упаковки"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,7,12,17), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("185"), new BigDecimal("6"), 40, "Покупка упаковки"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,6,15,8), "Очки Jagermeister Глянцевые Черные (старого образца)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("106"), new BigDecimal("0"), 40, "Карта клиента НП (+2 грн.)"), 101);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,5,16,42), "Doctors Best Гиалуроновая кислота и сульфат хондроитина 180 капсул", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.COMPLETE_PREPAYMENT, OrderStatusEnum.SUCCESS, new BigDecimal("310"), new BigDecimal("0"), 0, "Карта клиента НП (+2 грн.)"), 102);
			productRepository.save(new Product(null, LocalDateTime.of(2019,8,4,14,55), "Очки Jagermeister Black-Orange (Новые!)", MarketPlaceEnum.OLX, DeliveryServiceEnum.NOVA_POST, PaymentMethodEnum.OLX_DELIVERY, OrderStatusEnum.SUCCESS, new BigDecimal("185"), new BigDecimal("6"), 40, "Покупка упаковки"), 101);
		}
	}
}


